version: 2
formats:
    - htmlzip
    - pdf
build:
    os: ubuntu-24.04
    apt_packages:
        - libgmp-dev
        - build-essential
        - pkg-config
        - curl
    jobs:
      post_checkout:
        - git fetch --tags  # readthedocs/readthedocs.org#10715
      pre_create_environment:
        - sh scripts/cibw_before_all.sh --skip-gmp
    tools:
        python: "3"
python:
    install:
        - path: .
sphinx:
    fail_on_warning: true
    configuration: docs/conf.py
